opseq_tokenizer_config:
  max_seq_length: 35
  digit_precision_front: 1
  digit_precision_back: 2
  if_str_constant_code: True
  token_name:
    pad_token: "[PAD]"
    cls_token: "[CLS]"
    def_token: "[DEF]"
    eos_token: "[EOS]"
    bos_token: "[BOS]"
    enc_token: "[ENC]"
    sep_token: "[SEP]"
    mask_token: "[MASK]"
    unk_token: "[UNK]"
    dot_token: "[.]"
    comma_token: "[,]"
    neg_token: "[-]"


botfip_train_parameters:
  epoch_num: 200
  wandb_entity_name: jsmy
  wandb_project_name: botfip
  wandb_test_name: botfip_pretrain
  train_type: all
  step_size: 10
  gamma: 0.9
  weight_decay: 0.05
  init_lr: 1.0e-5
  init_steps: 0
  min_lr: 1.0e-6
  warmup_lr: 1.0e-6
  lr_decay_rate: 0.9
  warmup_steps: 2000
  batch_size: 25
  sample_points_num: 200
  device: cuda
  print_step: 20
  model_save_path: /home/cth/nfs_store/Botfip_checkpoint
  save_epoch: 2
  val_epoch: 5
  val_num: 400
  num_workers: 0
  load_path:



op_dataset_config:
  img_range: [-1,1]
  img_compress_range: [-0.95,0.95]
  num_of_formulas_skeleton: 200
  num_of_op_assign: 3
  num_of_constants_group: 30
  finetune_num_of_constants_group: 1000
  finetune_set_node_num: 8
  finetune_formula_num: 50
  max_region_num: 10
  max_node_range: [5,6]
  max_var_range: [-20,20]
  region_distance_range: [5,8]
  region_tensor_shape: 100
  chunk_size: 20
  multiscale: 3
  img_shape: 64
  dataset_path: /home/cth/nfs_store/dataset/new_formal_dataset_3
  val_dataset_path: /home/cth/nfs_store/dataset/new_formal_dataset_3
  finetune_dataset_path: /home/cth/nfs_store/dataset/new_formal_dataset_3


operation_tree_config:
  min_leaf_nodes:
  node_num: 12
  min_leaf_nodes_ratio: 0.2
  max_var_types: 2
  constants_ratio_range: [0.2, 0.4]
  constants_range: [-2, 2]
  unary_probability: 0.7
  max_constants_num: 10
  max_single_chain_length: 3
  variable_replace_probability: 0.8
  num_backend: numpy
  if_print: False
  operation_config_path: /home/cth/nfsroot/Botfip/configs/opeartion.yaml

blip_pretrain_config:
  queue_size: 24000
  alpha: 0.4
  embed_dim: 256
  momentum: 0.995
  tie_enc_dec_weights: False
  load_path:

bert_config:
  hidden_dropout_prob: 0.2
  attention_probs_dropout_prob: 0.2
  max_position_embeddings: 200
  hidden_size: 768
  encoder_width: 768
  num_attention_heads: 12
  num_hidden_layers: 10
  position_embedding_type: absolute
  layer_norm_eps: 1.0e-12
  chunk_size_feed_forward: 0
  add_cross_attention: True
  intermediate_size: 2048
  decoder_mlp_layers_num: 8
  hidden_act: 'gelu'

funcimg_encoder_config:
  region_range: [-10,10]
  image_size: 64
  vision_width: 768
  hidden_size: 768
  num_hidden_layers: 10
  dim_head: 64
  patch_size: 8
  num_class: 256
  channels: 3
  pool: cls
  layer_norm_eps: 0.1
  hidden_act: gelu
  num_attention_heads: 8
  hidden_dropout_prob: 0.
  intermediate_size: 2048
  digit_precision: -2
  if_coded: True

mlp_mixer_config:
  block_num: 3
  #num_hidden_layers: 5
  num_res_layers: 6
  layer_norm_eps: 1.0e-12
  block_ascend_ratio: 1.4
  block_descend_ratio: 0.3
  max_hidden_dim: 1200
  min_hidden_dim: 64
  res_ascend_ratio: 1.3
  res_descend_ratio: 0.5
  start_hidden_dim: 256
  hidden_dropout_prob: 0.2
  hidden_size: 256
  act_type: PReLU
  if_normal: False
  is_include_mlp_head: False













